const DEFAULT_NOTE_WIDTH = 360;
const DEFAULT_NOTE_HEIGHT = 220;

const MIN_NOTE_WIDTH = 280;
const MIN_NOTE_HEIGHT = 120;

module.exports = {
  DEFAULT_NOTE_WIDTH,
  DEFAULT_NOTE_HEIGHT,
  MIN_NOTE_WIDTH,
  MIN_NOTE_HEIGHT,
};
